name: Build-user-servlet-api-prd.yml

on:
  push:
    branches:
      - main  # 원하는 브랜치로 변경 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up application.properties
        run: |
          cat <<EOF > ./src/main/resources/application.properties
          ${{ secrets.APPLICATION }}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Confirm Docker Login
        run: docker info | grep Username || echo "⚠️ Docker not logged in!"

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t perasperaadastra250225/user-servlet-api:1.0.0 --push .

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull perasperaadastra250225/user-servlet-api:1.0.0
            docker stop user-servlet-api || true
            docker rm user-servlet-api || true
            docker run -d -p 8020:8020 --restart unless-stopped -v /home/ec2-user/user-servlet-api-log:/app/log --name user-servlet-api perasperaadastra250225/user-servlet-api:1.0.0
